" Magic spell
if &compatible
  set nocompatible
endif

" Clipboard register
if has('unnamedplus')
  set clipboard& clipboard+=unnamedplus
else
  set clipboard& clipboard+=unnamed
endif

" Backups
set nowritebackup
set nobackup
set noswapfile
set formatoptions=q

" Undo
set undofile
set undodir=~/.vim/undo

" Diff
set nodiff

" Line number
set nu

" Indent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent

" List
set list
if IsWindows()
  set listchars=tab:>-,trail:-,extends:>,precedes:<
else
  set listchars=tab:▸-,trail:-,extends:»,precedes:«,nbsp:%
endif

" Title
set title
set titlelen=90

" Status line
set laststatus=2

" Show cmd
set noshowcmd

" Parenthesis
set showmatch
set matchtime=2

" Case
set ignorecase
