" Magic spell
if &compatible
  set nocompatible
endif

" Clipboard register
if has('unnamedplus')
  set clipboard& clipboard=unnamedplus
else
  set clipboard& clipboard=unnamed
endif

" Backups
set nowritebackup
set nobackup
set noswapfile
set formatoptions=q

" Undo
set undofile
set undodir=~/.vim/undo

" Diff
set nodiff

" Case
set ignorecase

" Spell
" set spell
set spelllang=en,cjk
