include_recipe '../../lib/utils'

include_cookbook 'vim'
include_cookbook 'vimperator'
include_cookbook 'git'
include_cookbook 'zsh'
include_cookbook 'nvim'
include_cookbook 'idea'
include_cookbook 'tmux'
include_cookbook 'chunkwm'
# include_cookbook 'fish'
