# Reload .tmux.conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Disable bell
set-option -g bell-action none

# Set 256 color
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Prefix
unbind C-b
set -g prefix C-j
unbind C-a
unbind C-f

# Copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Use current directory
unbind \"
bind \" split-window -v -c '#{pane_current_path}'
unbind \%
bind \% split-window -h -c '#{pane_current_path}'

# Window index
set -g base-index 1

# Pane index
setw -g pane-base-index 1

# Key stroke
set -sg escape-time 1

# Set status line top
set -g status-position top

# ステータスバーを設定する
setw -g allow-rename off
setw -g window-status-current-format "#[fg=colour255,bg=colour241,bold] #I: #W #[default]"

## 左パネルを設定する
set -g status-left-length 50
set -g status-left \
"#{?client_prefix,#[reverse],}#[fg=green][#S] #{?window_zoomed_flag,[🔎],} "

## 右パネルを設定する
set -g status-right-length 100
set -g status-right \
"#[fg=red][#(kubectl config current-context)/#(kubectl config view --minify -o \"jsonpath={..namespace}\")] #[fg=cyan][%Y-%m-%d(%a) %H:%M]"

# default statusbar colors
set-option -g status-bg black #base02
set-option -g status-fg yellow #yellow
set-option -g status-style default
# default window title colors
setw -g window-status-style fg=brightblue,bg=default
# active window title colors
setw -g window-status-current-style fg=brightred,bg=default
# pane border
set-option -g pane-border-style fg=black
set-option -g pane-active-border-style fg=brightgreen
# message text
set-option -g message-style bg=black,fg=brightred

# save session
set -g @tpm_plugins '         \
  tmux-plugins/tpm            \
  tmux-plugins/tmux-resurrect \
  tmux-plugins/tmux-continuum \
'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'iterm,fullscreen'
set -g @continuum-save-interval '60'
set -g @continuum-restore 'on'

# run plugin manager
run '~/.tmux/plugins/tpm/tpm'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
