font:
  normal:
    family: SauceCodePro Nerd Font Mono
    style: Regular
  bold:
    family: SauceCodePro Nerd Font Mono
    style: Bold
  italic:
    family: SauceCodePro Nerd Font Mono
    style: Italic
  size: 18.0
window:
  opacity: 1.0
