"------------------------------------------------------
" vimrc

" Magic spell
if &compatible
  set nocompatible
endif

" Clipboard register
if has('unnamedplus')
  set clipboard& clipboard=unnamedplus
else
  set clipboard& clipboard=unnamed
endif

" Backups
set nowritebackup
set nobackup
set noswapfile
set formatoptions=q

" Undo
set undofile
set undodir=$XDG_CONFIG_HOME/nvim/undo

" Case
set ignorecase

" Backspace
set backspace=indent,eol,start

" Mouse
set mouse=a

" Fold
set foldmethod=marker

" fast scroll
set lazyredraw
set ttyfast

set ttimeout
set ttimeoutlen=50

if has('conceal')
  set conceallevel=0
endif

set nowrap

" Hardway
" noremap h <NOP>
" noremap l <NOP>
